### ISSUE TITLE
Error while installing.

### ISSUE THREAD

**Issue by NeoTech** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#25]
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: K:\LLM\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
Traceback (most recent call last):
  File "K:\LLM\ComfyUI\nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\LLM\ComfyUI\custom_nodes\PowerNoiseSuite\__init__.py", line 5, in <module>
    print(f"\033[1;32m[Power Noise Suite]: \U0001f99a\U0001f99a\U0001f99a \033[93m\033[3m{random.choice(peacock_rambling)}\033[0m \U0001f99a\U0001f99a\U0001f99a")
  File "K:\LLM\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 118, in write
    self.sync_write(message)
  File "K:\LLM\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 126, in sync_write
    original_stdout.write(message)
  File "C:\Users\andre\anaconda3\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 28-30: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\LLM\ComfyUI\main.py", line 164, in <module>
    init_custom_nodes()
  File "K:\LLM\ComfyUI\nodes.py", line 1873, in init_custom_nodes
    load_custom_nodes()
  File "K:\LLM\ComfyUI\nodes.py", line 1834, in load_custom_nodes
    success = load_custom_node(module_path, base_node_names)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\LLM\ComfyUI\nodes.py", line 1816, in load_custom_node
    print(traceback.format_exc())
  File "K:\LLM\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 118, in write
    self.sync_write(message)
  File "K:\LLM\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 126, in sync_write
    original_stdout.write(message)
  File "C:\Users\andre\anaconda3\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 431-433: character maps to <undefined>

**Comment by omar92** [comment]
kindly tell me if it works now
