### ISSUE TITLE
[FYI] unable to find __init__py for legacy nodes with non-portable path [low priority]

### ISSUE THREAD

**Issue by wyrde** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#3]
Errors when archiving legacy nodes. I'm sure it has something to do with the paths I changed in QualityOfLifeSuit_Omar92.py and QualityOfLife_deprecatedNodes.py since I don't use the portable paths.

It only happens the first time, though, and the replaced nodes are archived. I'm guessing it isn't critical.

```
QualityOflife Node Suite: Found legacy nodes. Archiving legacy nodes...
QualityOflife Node Suite: Legacy cleanup complete.
QualityOfLifeSuit_Omar92_DIR: D:\dev\sd.comfy\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92\src\..
Traceback (most recent call last):
  File "D:\dev\sd.comfy\nodes.py", line 1119, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\dev\\sd.comfy\\custom_nodes\\LatentUpscaleMultiply_Omar92.py\\__init__.py'

Cannot import D:\dev\sd.comfy\custom_nodes\LatentUpscaleMultiply_Omar92.py module for custom nodes: [Errno 2] No such file or directory: 'D:\\dev\\sd.comfy\\custom_nodes\\LatentUpscaleMultiply_Omar92.py\\__init__.py'
Traceback (most recent call last):
  File "D:\dev\sd.comfy\nodes.py", line 1119, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\dev\\sd.comfy\\custom_nodes\\StringSuit_Omar92.py\\__init__.py'

Cannot import D:\dev\sd.comfy\custom_nodes\StringSuit_Omar92.py module for custom nodes: [Errno 2] No such file or directory: 'D:\\dev\\sd.comfy\\custom_nodes\\StringSuit_Omar92.py\\__init__.py'
```

**Comment by omar92** [comment]
your edit works fine for me so i merged it XD

**Comment by wyrde** [comment]
then we'll close it (:
